package com.test.poc_test;

import com.test.poc_test.POC2_1;
import java.util.List
import java.util.ArrayList

rule "POC passed"
    when
        $listOfData : ArrayList()
        $POC : POC2_1(ap_price > 3000 && level == "3" && ap_price_percent > 0.8 && mp_max_price < 1000) from $listOfData
    then
        $POC.setStatus(true);
        // update($s);
end

rule "POC failed"
    when
        $listOfData : ArrayList()
        $POC : POC2_1(ap_price <= 3000 || level > 6 || ap_price_percent <= 0.8 || mp_max_price >= 1000) from $listOfData
    then
        $POC.setStatus(false);
        // update($s);
end

rule "POC NULL"
    when
        $listOfData : ArrayList()
        $POC : POC2_1(ap_price == null || level == null || ap_price_percent == null || mp_max_price == null) from $listOfData
    then
        $POC.setStatus(false);
        // update($s);
end
