package com.test.poc_test;
import java.util.*;
import java.lang.*;
import com.fasterxml.jackson.databind.*;
import org.json.*;
/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class POC2_2 implements java.io.Serializable {

	static final long serialVersionUID = 1;

	@org.kie.api.definition.type.Label("Product Price")
	private java.lang.Double product_price;
	@org.kie.api.definition.type.Label("AGM price")
	private java.lang.Integer Agm_price;
	@org.kie.api.definition.type.Label("購買類型")
	private java.lang.Integer purchase_type ;
// 	@org.kie.api.definition.type.Label("GP首購")
// 	private boolean gp_first;
// 	@org.kie.api.definition.type.Label("MP首購")
// 	private boolean mp_first;
	@org.kie.api.definition.type.Label("age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("Request status")
	private boolean status;
	public POC2_2() {
	}

	public double getproduct_price() {

		return this.product_price;
	}

	public void setproduct_price(java.lang.Double product_price) {
	    
		this.product_price = product_price;
	}
	
	public int getAgm_price() {
	    
		return this.Agm_price;
	}

	public void setAgm_price(java.lang.Integer Agm_price) {

		this.Agm_price = Agm_price;
	}
	
	public java.lang.Integer getpurchase_type() {

		return this.purchase_type;
	}

	public void setpurchase_type(java.lang.Integer purchase_type) {
		this.purchase_type = purchase_type;
	}
	
	public int getage() {
		return this.age;
	}

	public void setage(java.lang.Integer age) {

		this.age = age;
	}
	
	public boolean getStatus() {
	   // level = 4;
	    System.out.println("Get Status:"+status);
		return this.status;
	}
	
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
	   // System.out.println(status);
		this.status = status;
	}
	
	
	public POC2_2(java.lang.Double product_price,
	        java.lang.Integer Agm_price,
	        java.lang.Integer purchase_type,boolean status,java.lang.Integer age) {
        this.product_price = product_price;
        this.Agm_price = Agm_price;
        this.purchase_type = purchase_type;
        this.age = age;
		this.status = status;
		
	}
    
}
