package com.test.poc_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class POC2_2 implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public POC2_2() {
    }




}